//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akıllı_Jammer_Karar_Destek_Arayüzü.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8192")]
        public int BufferBoyutu {
            get {
                return ((int)(this["BufferBoyutu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int SinyalGenligi {
            get {
                return ((int)(this["SinyalGenligi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128")]
        public int KareDalgaPeriyodu {
            get {
                return ((int)(this["KareDalgaPeriyodu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DahiliTestKazanci {
            get {
                return ((int)(this["DahiliTestKazanci"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int DonanimZamanAsimi {
            get {
                return ((int)(this["DonanimZamanAsimi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8192")]
        public int TxBufferBoyutu {
            get {
                return ((int)(this["TxBufferBoyutu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int TxZamanAsimiMs {
            get {
                return ((int)(this["TxZamanAsimiMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8192")]
        public int RxBufferBoyutu {
            get {
                return ((int)(this["RxBufferBoyutu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int RxNumBuffers {
            get {
                return ((int)(this["RxNumBuffers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int RxNumTransfers {
            get {
                return ((int)(this["RxNumTransfers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int RxZamanAsimiMs {
            get {
                return ((int)(this["RxZamanAsimiMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int HataBeklemeMs {
            get {
                return ((int)(this["HataBeklemeMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70000000")]
        public long MinFrekansHz {
            get {
                return ((long)(this["MinFrekansHz"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6000000000")]
        public long MaxFrekansHz {
            get {
                return ((long)(this["MaxFrekansHz"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61440000")]
        public int MaxOrneklemeHz {
            get {
                return ((int)(this["MaxOrneklemeHz"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public int MinBantGenisligi {
            get {
                return ((int)(this["MinBantGenisligi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56000000")]
        public int MaxBantGenisligi {
            get {
                return ((int)(this["MaxBantGenisligi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.30")]
        public decimal BantKirpmaYuzdesi {
            get {
                return ((decimal)(this["BantKirpmaYuzdesi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int TxRxGecisSuresiMs {
            get {
                return ((int)(this["TxRxGecisSuresiMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM] Cihaza bağlanılıyor...")]
        public string LOG_BAGLANIYOR {
            get {
                return ((string)(this["LOG_BAGLANIYOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM] Canlı dinleme BAŞLATILDI...")]
        public string LOG_CANLI_DINLEME {
            get {
                return ((string)(this["LOG_CANLI_DINLEME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SİNYALİ KES")]
        public string UI_BTN_SINYALI_KES {
            get {
                return ((string)(this["UI_BTN_SINYALI_KES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DİKKAT: TAARRUZ MODU SEÇİLDİ (SİLAH KURULU)")]
        public string UI_MOD_TAARRUZ {
            get {
                return ((string)(this["UI_MOD_TAARRUZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cihaz bulunamadı veya açılamadı! USB bağlantısını kontrol edin. ")]
        public string ERR_CIHAZ_BULUNAMADI {
            get {
                return ((string)(this["ERR_CIHAZ_BULUNAMADI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEMİZ - DİNLENİYOR... ")]
        public string STATUS_MOD_DINLEME {
            get {
                return ((string)(this["STATUS_MOD_DINLEME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DİKKAT: TAARRUZ MODU SEÇİLDİ (SİLAH KURULU)")]
        public string STATUS_MOD_TAARRUZ {
            get {
                return ((string)(this["STATUS_MOD_TAARRUZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GÜVENLİ MOD: DAHİLİ TEST (LOOPBACK) AKTİF")]
        public string STATUS_MOD_TEST {
            get {
                return ((string)(this["STATUS_MOD_TEST"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALARM SİSTEMİ DEVRE DIŞI")]
        public string STATUS_ALARM_KAPALI {
            get {
                return ((string)(this["STATUS_ALARM_KAPALI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SALDIRI BAŞLAT")]
        public string UI_BTN_SALDIRI_BASLAT {
            get {
                return ((string)(this["UI_BTN_SALDIRI_BASLAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEST SİNYALİ GÖNDER")]
        public string UI_BTN_TEST_GONDER {
            get {
                return ((string)(this["UI_BTN_TEST_GONDER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("🔌")]
        public string UI_BTN_BAGLAN {
            get {
                return ((string)(this["UI_BTN_BAGLAN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("⏹")]
        public string UI_BTN_DURDUR {
            get {
                return ((string)(this["UI_BTN_DURDUR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("▶")]
        public string UI_BTN_DEVAM {
            get {
                return ((string)(this["UI_BTN_DEVAM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("➕ Yeni Özel Ayar Kaydet...")]
        public string UI_PROFIL_YENI_KAYDET {
            get {
                return ((string)(this["UI_PROFIL_YENI_KAYDET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dil Seçimi (Language)")]
        public string MENU_DIL_SECIMI {
            get {
                return ((string)(this["MENU_DIL_SECIMI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tema Seçimi (Theme)")]
        public string MENU_TEMA_SECIMI {
            get {
                return ((string)(this["MENU_TEMA_SECIMI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ayar Klasörünü Aç (Dosyaları Buraya Atın)")]
        public string MENU_KLASOR_AC {
            get {
                return ((string)(this["MENU_KLASOR_AC"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dosya bulunamadı!")]
        public string MENU_DOSYA_YOK {
            get {
                return ((string)(this["MENU_DOSYA_YOK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[TX AKTİF] Sistem üzerinden fiziksel sinyal gönderiliyor...")]
        public string LOG_TX_AKTIF {
            get {
                return ((string)(this["LOG_TX_AKTIF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[TX KAPATILDI] Gönderim kesildi. Beklemede.")]
        public string LOG_TX_KAPALI {
            get {
                return ((string)(this["LOG_TX_KAPALI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[DONANIM] Parametreler uygulandı! Yeni SR:")]
        public string LOG_PARAMETRE_UYGULANDI {
            get {
                return ((string)(this["LOG_PARAMETRE_UYGULANDI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yüklendi.")]
        public string LOG_PROFIL_YUKLENDI {
            get {
                return ((string)(this["LOG_PROFIL_YUKLENDI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM] Taktik Profil: DRONE (2.4 GHz)")]
        public string LOG_PROFIL_DRONE {
            get {
                return ((string)(this["LOG_PROFIL_DRONE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM] Taktik Profil: TELSİZ (433 MHz)")]
        public string LOG_PROFIL_TELSIZ {
            get {
                return ((string)(this["LOG_PROFIL_TELSIZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM] Taktik Profil: GSM / LTE TELEFON")]
        public string LOG_PROFIL_TELEFON {
            get {
                return ((string)(this["LOG_PROFIL_TELEFON"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[DONANIM HATASI]")]
        public string ERR_DONANIM_HATASI {
            get {
                return ((string)(this["ERR_DONANIM_HATASI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TX Hatası:")]
        public string ERR_TX_HATASI {
            get {
                return ((string)(this["ERR_TX_HATASI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Geçiş hatası:")]
        public string ERR_GECIS_HATASI {
            get {
                return ((string)(this["ERR_GECIS_HATASI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yetki Reddedildi")]
        public string MSG_YETKI_BASLIK {
            get {
                return ((string)(this["MSG_YETKI_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Taktik (Askeri) modda sisteme yeni ayar kaydedilemez!\\nLütfen İleri Mühendis Modu" +
            "na geçiş yapın.")]
        public string MSG_YETKI_METIN {
            get {
                return ((string)(this["MSG_YETKI_METIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yeni Profil Adını Girin:")]
        public string MSG_PROFIL_ADI_GIRIN {
            get {
                return ((string)(this["MSG_PROFIL_ADI_GIRIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profil Kaydet")]
        public string MSG_PROFIL_KAYDET_BASLIK {
            get {
                return ((string)(this["MSG_PROFIL_KAYDET_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bu isimde bir profil zaten var!")]
        public string ERR_PROFIL_ZATEN_VAR {
            get {
                return ((string)(this["ERR_PROFIL_ZATEN_VAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Başarıyla Kaydedildi!")]
        public string MSG_BASARIYLA_KAYDEDILDI {
            get {
                return ((string)(this["MSG_BASARIYLA_KAYDEDILDI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hata")]
        public string MSG_HATA_BASLIK {
            get {
                return ((string)(this["MSG_HATA_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bilgi")]
        public string MSG_BILGI_BASLIK {
            get {
                return ((string)(this["MSG_BILGI_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kritik JSON Hatası")]
        public string ERR_JSON_BASLIK {
            get {
                return ((string)(this["ERR_JSON_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DİL DOSYASINDA YAZIM HATASI VAR!\\nDosya: {0}\\nDetay: {1}\\n\\nLütfen JSON dosyasınd" +
            "aki virgül ve tırnak işaretlerini kontrol edin.")]
        public string ERR_JSON_DIL_METIN {
            get {
                return ((string)(this["ERR_JSON_DIL_METIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TEMA DOSYASINDA YAZIM HATASI VAR!\\nDosya: {0}\\nDetay: {1}\\n\\nLütfen JSON dosyasın" +
            "daki virgül ve tırnak işaretlerini kontrol edin.")]
        public string ERR_JSON_TEMA_METIN {
            get {
                return ((string)(this["ERR_JSON_TEMA_METIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int KapanisZamanAsimiIterasyon {
            get {
                return ((int)(this["KapanisZamanAsimiIterasyon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int KapanisBeklemeMs {
            get {
                return ((int)(this["KapanisBeklemeMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ModGecisZamanAsimiIterasyon {
            get {
                return ((int)(this["ModGecisZamanAsimiIterasyon"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ModGecisBeklemeMs {
            get {
                return ((int)(this["ModGecisBeklemeMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int DinamikAyarGecikmesiMs {
            get {
                return ((int)(this["DinamikAyarGecikmesiMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int OtopilotBeklemeMs {
            get {
                return ((int)(this["OtopilotBeklemeMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int KalibrasyonBeklemeMs {
            get {
                return ((int)(this["KalibrasyonBeklemeMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("🗑 Seçili Özel Profili Sil")]
        public string MENU_PROFIL_SIL {
            get {
                return ((string)(this["MENU_PROFIL_SIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'{0}\' profilini silmek istediğinize emin misiniz?")]
        public string MSG_PROFIL_SIL_ONAY {
            get {
                return ((string)(this["MSG_PROFIL_SIL_ONAY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Profil Sil")]
        public string MSG_PROFIL_SIL_BASLIK {
            get {
                return ((string)(this["MSG_PROFIL_SIL_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM] {0} başarıyla silindi.")]
        public string LOG_PROFIL_SILINDI {
            get {
                return ((string)(this["LOG_PROFIL_SILINDI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sadece kendi kaydettiğiniz özel profilleri silebilirsiniz!")]
        public string MSG_SADECE_OZEL_PROFIL_SILINIR {
            get {
                return ((string)(this["MSG_SADECE_OZEL_PROFIL_SILINIR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Uyarı")]
        public string MSG_UYARI_BASLIK {
            get {
                return ((string)(this["MSG_UYARI_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATEL Karar Destek - [İLERİ MÜHENDİS MODU]")]
        public string UI_MOD_MUHENDIS_BASLIK {
            get {
                return ((string)(this["UI_MOD_MUHENDIS_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TAKTİK MODA DÖN")]
        public string UI_BTN_TAKTIK_MODA_DON {
            get {
                return ((string)(this["UI_BTN_TAKTIK_MODA_DON"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATEL Karar Destek - [TAKTİK (ASKERİ) MOD]")]
        public string UI_MOD_TAKTIK_BASLIK {
            get {
                return ((string)(this["UI_MOD_TAKTIK_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("İLERİ MOD AKTİF")]
        public string UI_BTN_ILERI_MOD_AKTIF {
            get {
                return ((string)(this["UI_BTN_ILERI_MOD_AKTIF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[OTOPİLOT] Cihaza otomatik bağlanılıyor...")]
        public string LOG_OTOPILOT_BAGLANILIYOR {
            get {
                return ((string)(this["LOG_OTOPILOT_BAGLANILIYOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[OTOPİLOT] Veri akışı başlatılıyor...")]
        public string LOG_OTOPILOT_AKIS_BASLIYOR {
            get {
                return ((string)(this["LOG_OTOPILOT_AKIS_BASLIYOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM] İzleme geçici olarak durduruldu.")]
        public string LOG_IZLEME_DURDURULDU {
            get {
                return ((string)(this["LOG_IZLEME_DURDURULDU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[HATA] İşlem başarısız: {0}")]
        public string LOG_ISLEM_BASARISIZ {
            get {
                return ((string)(this["LOG_ISLEM_BASARISIZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KALİBRE EDİLİYOR...")]
        public string UI_BTN_KALIBRE_EDILIYOR {
            get {
                return ((string)(this["UI_BTN_KALIBRE_EDILIYOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[DONANIM] DC Offset (LO Leakage) Kalibrasyonu başlatıldı. Lütfen bekleyin...")]
        public string LOG_KALIBRASYON_BASLADI {
            get {
                return ((string)(this["LOG_KALIBRASYON_BASLADI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM] Kalibrasyon tamamlandı! Merkez frekanstaki (DC) parazit temizlendi.")]
        public string LOG_KALIBRASYON_BITTI {
            get {
                return ((string)(this["LOG_KALIBRASYON_BITTI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bağlantı Hatası")]
        public string MSG_BAGLANTI_HATASI_BASLIK {
            get {
                return ((string)(this["MSG_BAGLANTI_HATASI_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cihaz bağlı değil! Lütfen önce cihaza bağlanın.")]
        public string MSG_CIHAZ_BAGLI_DEGIL {
            get {
                return ((string)(this["MSG_CIHAZ_BAGLI_DEGIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<- Alt Frekanslar")]
        public string UI_GRAFIK_ALT_FREKANSLAR {
            get {
                return ((string)(this["UI_GRAFIK_ALT_FREKANSLAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Üst Frekanslar ->")]
        public string UI_GRAFIK_UST_FREKANSLAR {
            get {
                return ((string)(this["UI_GRAFIK_UST_FREKANSLAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Henüz kaydedilmiş bir tehdit verisi yok! Sistem temiz.")]
        public string MSG_RAPOR_BOS {
            get {
                return ((string)(this["MSG_RAPOR_BOS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rapor Hazır ")]
        public string MSG_RAPOR_HAZIR_BASLIK {
            get {
                return ((string)(this["MSG_RAPOR_HAZIR_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Görev Raporu başarıyla oluşturuldu!\\n\\nDosya Masaüstüne Kaydedildi:\\n{0}")]
        public string MSG_RAPOR_BASARILI {
            get {
                return ((string)(this["MSG_RAPOR_BASARILI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Raporlama Hatası")]
        public string MSG_RAPOR_HATA_BASLIK {
            get {
                return ((string)(this["MSG_RAPOR_HATA_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rapor oluşturulurken bir hata meydana geldi:\\n\\n{0}")]
        public string MSG_RAPOR_HATA_METIN {
            get {
                return ((string)(this["MSG_RAPOR_HATA_METIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("▼ M1: {0:F4} MHz")]
        public string UI_MARKER_METIN {
            get {
                return ((string)(this["UI_MARKER_METIN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int GerekliSureklilik {
            get {
                return ((int)(this["GerekliSureklilik"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DJI Drone / Wi-Fi (2.4 GHz)")]
        public string UI_PROFIL_DRONE {
            get {
                return ((string)(this["UI_PROFIL_DRONE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Taktik Telsiz (UHF 433 MHz)")]
        public string UI_PROFIL_TELSIZ {
            get {
                return ((string)(this["UI_PROFIL_TELSIZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GSM / LTE Telefon (1.75 GHz)")]
        public string UI_PROFIL_TELEFON {
            get {
                return ((string)(this["UI_PROFIL_TELEFON"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SistemAyarlari.json")]
        public string DOSYA_AYARLAR {
            get {
                return ((string)(this["DOSYA_AYARLAR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tehdit_Raporlari.csv")]
        public string DOSYA_LOG_CSV {
            get {
                return ((string)(this["DOSYA_LOG_CSV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dil_Turkce.json")]
        public string VARSAYILAN_DIL {
            get {
                return ((string)(this["VARSAYILAN_DIL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tema_Varsayilan.json")]
        public string VARSAYILAN_TEMA {
            get {
                return ((string)(this["VARSAYILAN_TEMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tarih_Saat;Merkez_Frekans_MHz;Sinyal_Gucu_dB;Tehdit_Esigi_dB;Bant_Genisligi_MHz;O" +
            "rnekleme_Hizi_MSps")]
        public string CSV_BASLIK_SATIRI {
            get {
                return ((string)(this["CSV_BASLIK_SATIRI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.4")]
        public decimal DroneFrekans {
            get {
                return ((decimal)(this["DroneFrekans"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22.0")]
        public decimal DroneOrnekleme {
            get {
                return ((decimal)(this["DroneOrnekleme"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20.0")]
        public decimal DroneBant {
            get {
                return ((decimal)(this["DroneBant"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("433.0")]
        public decimal TelsizFrekans {
            get {
                return ((decimal)(this["TelsizFrekans"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public decimal TelsizOrnekleme {
            get {
                return ((decimal)(this["TelsizOrnekleme"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.0")]
        public decimal TelsizBant {
            get {
                return ((decimal)(this["TelsizBant"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1750.0")]
        public decimal TelefonFrekans {
            get {
                return ((decimal)(this["TelefonFrekans"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.0")]
        public decimal TelefonOrnekleme {
            get {
                return ((decimal)(this["TelefonOrnekleme"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public decimal TelefonBant {
            get {
                return ((decimal)(this["TelefonBant"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GHz")]
        public string BIRIM_GHZ {
            get {
                return ((string)(this["BIRIM_GHZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MHz")]
        public string BIRIM_MHZ {
            get {
                return ((string)(this["BIRIM_MHZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MSps")]
        public string BIRIM_MSPS {
            get {
                return ((string)(this["BIRIM_MSPS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} ms")]
        public string FORMAT_MS {
            get {
                return ((string)(this["FORMAT_MS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM]")]
        public string LOG_SISTEM_ON_EK {
            get {
                return ((string)(this["LOG_SISTEM_ON_EK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\n")]
        public string YENI_SATIR {
            get {
                return ((string)(this["YENI_SATIR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kHz")]
        public string BIRIM_KHZ {
            get {
                return ((string)(this["BIRIM_KHZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kSps")]
        public string BIRIM_KSPS {
            get {
                return ((string)(this["BIRIM_KSPS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("k")]
        public string KISA_K {
            get {
                return ((string)(this["KISA_K"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string KISA_M {
            get {
                return ((string)(this["KISA_M"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string KISA_G {
            get {
                return ((string)(this["KISA_G"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public double CarpanMega {
            get {
                return ((double)(this["CarpanMega"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000000")]
        public double CarpanGiga {
            get {
                return ((double)(this["CarpanGiga"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31200000")]
        public double VarsayilanOrneklemeHz {
            get {
                return ((double)(this["VarsayilanOrneklemeHz"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000000")]
        public double VarsayilanBantHz {
            get {
                return ((double)(this["VarsayilanBantHz"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double BolenYari {
            get {
                return ((double)(this["BolenYari"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double YuzdeBolen {
            get {
                return ((double)(this["YuzdeBolen"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048")]
        public double FftOlcekBoleni {
            get {
                return ((double)(this["FftOlcekBoleni"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double DbHesapCarpani {
            get {
                return ((double)(this["DbHesapCarpani"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1E-10")]
        public double MathLogSifirKorumasi {
            get {
                return ((double)(this["MathLogSifirKorumasi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double GrafikVarsayilanMaxDb {
            get {
                return ((double)(this["GrafikVarsayilanMaxDb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-120")]
        public double GrafikVarsayilanMinDb {
            get {
                return ((double)(this["GrafikVarsayilanMinDb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-40")]
        public double VarsayilanTehditEsigiDb {
            get {
                return ((double)(this["VarsayilanTehditEsigiDb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-80")]
        public double VarsayilanGurultuEsigiDb {
            get {
                return ((double)(this["VarsayilanGurultuEsigiDb"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int GridYatayKareSayisi {
            get {
                return ((int)(this["GridYatayKareSayisi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int GridDikeyKareSayisi {
            get {
                return ((int)(this["GridDikeyKareSayisi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int VarsayilanTxKazanci {
            get {
                return ((int)(this["VarsayilanTxKazanci"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kalibrasyon hatası:")]
        public string ERR_KALIBRASYON_HATASI {
            get {
                return ((string)(this["ERR_KALIBRASYON_HATASI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Log yazılamadı:")]
        public string ERR_LOG_YAZILAMADI {
            get {
                return ((string)(this["ERR_LOG_YAZILAMADI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sistem hafızası kaydedilemedi:")]
        public string ERR_AYAR_KAYDEDILEMEDI {
            get {
                return ((string)(this["ERR_AYAR_KAYDEDILEMEDI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kayıt Hatası")]
        public string ERR_KAYIT_BASLIK {
            get {
                return ((string)(this["ERR_KAYIT_BASLIK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Görev Raporu")]
        public string EXCEL_SAYFA_ADI {
            get {
                return ((string)(this["EXCEL_SAYFA_ADI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gorev_Sonu_Raporu_{0}.xlsx")]
        public string EXCEL_DOSYA_SABLONU {
            get {
                return ((string)(this["EXCEL_DOSYA_SABLONU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Kaydet")]
        public string UI_BTN_KAYDET {
            get {
                return ((string)(this["UI_BTN_KAYDET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double CarpanKilo {
            get {
                return ((double)(this["CarpanKilo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("☢ EŞİK DEĞERİNİN ÜSTÜNDE SİNYAL ALGILANDI! ☢")]
        public string STATUS_SINYAL_BASILIYOR {
            get {
                return ((string)(this["STATUS_SINYAL_BASILIYOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}dB")]
        public string FORMAT_YUZDE {
            get {
                return ((string)(this["FORMAT_YUZDE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15000")]
        public short CwTaarruzGenlik {
            get {
                return ((short)(this["CwTaarruzGenlik"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public double CwTaarruzFrekansKaymasiHz {
            get {
                return ((double)(this["CwTaarruzFrekansKaymasiHz"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8192")]
        public uint DonanimTxBuffer {
            get {
                return ((uint)(this["DonanimTxBuffer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint DonanimTxZamanAsimiMs {
            get {
                return ((uint)(this["DonanimTxZamanAsimiMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TX (Saldırı) RF Parametreleri")]
        public string UI_GRP_TX_PARAM {
            get {
                return ((string)(this["UI_GRP_TX_PARAM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hedef Profilleri")]
        public string UI_GRP_HEDEF_PROFILLERI {
            get {
                return ((string)(this["UI_GRP_HEDEF_PROFILLERI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TAARRUZ AKTİF!")]
        public string STATUS_TAARRUZ_AKTIF {
            get {
                return ((string)(this["STATUS_TAARRUZ_AKTIF"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM] ANA SİLAH: Sürekli Dalga (CW) Taarruzu Başlatıldı!")]
        public string LOG_ANA_SILAH_CW {
            get {
                return ((string)(this["LOG_ANA_SILAH_CW"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[TX DURDU] Hata Kodu: {0} (Cihaz tıkandı)")]
        public string LOG_TX_DURDU {
            get {
                return ((string)(this["LOG_TX_DURDU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[TX KAPATILDI] Gönderim kesildi. Beklemede.")]
        public string LOG_TX_KAPATILDI {
            get {
                return ((string)(this["LOG_TX_KAPATILDI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("İzleme geçici olarak durduruldu.")]
        public string LOG_IZLEME_GECICI_DURDURULDU {
            get {
                return ((string)(this["LOG_IZLEME_GECICI_DURDURULDU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RX (Dinleme) RF Parametreleri")]
        public string UI_GRP_RX_PARAM {
            get {
                return ((string)(this["UI_GRP_RX_PARAM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[SİSTEM KRİZİ]")]
        public string ERR_SISTEM_KRIZI {
            get {
                return ((string)(this["ERR_SISTEM_KRIZI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int TxBaslamaGecikmesiMs {
            get {
                return ((int)(this["TxBaslamaGecikmesiMs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public uint DonanimTxNumBuffers {
            get {
                return ((uint)(this["DonanimTxNumBuffers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public uint DonanimTxNumTransfers {
            get {
                return ((uint)(this["DonanimTxNumTransfers"]));
            }
        }
    }
}
